### ISSUE TITLE
Example to use ebook-convert

### ISSUE THREAD

**Issue by hungdev** [BlackHole1/get-calibre-tools#7]
hi guy. thank for your library.
But i don't know how to convert ebook after .then(path => { })
Could you give me an example.
https://manual.calibre-ebook.com/generated/en/ebook-convert.html

Thank you so much <3
@BlackHole1

**Comment by BlackHole1** [comment]
This package is just a package for getting the absolute path of the calibre tool.

If you want to know the address of ebook-convert, you can do the following:

```js
getCalibreTools('ebook-convert')
  .catch(e => {
    console.error(e);
  })
  .then(path => {
    console.log(path) // => Ebook-convert absolute path
  });
```

I don't know if I understand what you mean. If you understand it wrong, please let me know.

**Comment by hungdev** [comment]
@BlackHole1  thank your reply.
I thought that your library took the path of the tool and used caliber tool to convert ebook. And I want to convert .azw3 file to .mobi file. Do you know how to combine your library and caliber tool to convert ebook file?

**Comment by BlackHole1** [comment]
after getting the absolute path, you can use the nodejs api:
`exec` `execFile` `execSync` `execFileSync` `spawn` `spawnSync`
The documentation for the api is here: https://nodejs.org/api/child_process.html

You can use these apis to call these tools. The parameters of the tool are here:
https://manual.calibre-ebook.com/generated/en/ebook-convert.html

I have other examples here, you can take a look: https://github.com/Calibre-Node/ebook-rename/blob/master/index.js#L44-L66

**Comment by hungdev** [comment]
Thank you.
